apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: apache
  name: {{ .Values.apache.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.apache.deployment.replicasCount }}
  selector:
    matchLabels:
      run: apache
  strategy: {}
  template:
    metadata:
      labels:
        run: apache
    spec:
      containers:
        - image: {{ .Values.apache.deployment.image }}:{{ .Values.apache.deployment.tag }}
          name: apache
          ports:
            - containerPort: 80
          resources: {}
