apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: catalog
  name: {{ .Values.catalog.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.catalog.deployment.replicasCount }}
  selector:
    matchLabels:
      run: catalog
  strategy: {}
  template:
    metadata:
      labels:
        run: catalog
    spec:
      containers:
        - image: {{ .Values.catalog.deployment.image }}:{{ .Values.catalog.deployment.tag }}
          name: catalog
          ports:
            - containerPort: 8080
          resources: {}