apiVersion: v1
kind: Service
metadata:
  labels:
    run: catalog
  name: catalog
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: catalog
  type: {{ .Values.catalog.service.type }}