apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: customer
  name: {{ .Values.customer.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.customer.deployment.replicasCount }}
  selector:
    matchLabels:
      run: customer
  strategy: {}
  template:
    metadata:
      labels:
        run: customer
    spec:
      containers:
        - image: {{ .Values.customer.deployment.image }}:{{ .Values.customer.deployment.tag }}
          name: customer
          ports:
            - containerPort: 8080
          resources: {}