apiVersion: v1
kind: Service
metadata:
  labels:
    run: customer
  name: customer
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: customer
  type: {{ .Values.customer.service.type }}