apiVersion: v1
kind: Service
metadata:
  labels:
    run: order
  name: order
  namespace: {{ .Values.namespace }}
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    run: order
  type: {{ .Values.order.service.type }}