apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: order
  name: {{ .Values.order.deployment.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.order.deployment.replicasCount }}
  selector:
    matchLabels:
      run: order
  strategy: {}
  template:
    metadata:
      labels:
        run: order
    spec:
      containers:
        - image: {{ .Values.order.deployment.image }}:{{ .Values.order.deployment.tag }}
          name: order
          ports:
            - containerPort: 8080
          resources: {}