# Default values for cw.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

namespace: cw

apache:
  deployment:
    name: apache
    replicasCount: 1
    image: k8sacrcw1.azurecr.io/microservice-kubernetes-demo-apache
    tag: latest
  service:
    type: LoadBalancer
    loadbalancerip:


catalog:
  deployment:
    name: catalog
    replicasCount: 1
    image: k8sacrcw1.azurecr.io/microservice-kubernetes-demo-catalog
    tag: latest
  service:
    type: LoadBalancer

customer:
  deployment:
    name: customer
    replicasCount: 1
    image: k8sacrcw1.azurecr.io/microservice-kubernetes-demo-customer
    tag: latest
  service:
    type: LoadBalancer

order:
  deployment:
    name: order
    replicasCount: 1
    image: k8sacrcw1.azurecr.io/microservice-kubernetes-demo-order
    tag: latest
  service:
    type: LoadBalancer